<?php
return <<<END
<h2>Welcome!</h2>
<p>Welcome to collabor8r.com! It's a great place to find, discuss, and share academically interesting non-academic media. We hope you find our site useful and informative. Please feel free to contact us if you have comments, suggestions, or would just like to say hello.<br>
<a href="http://collabor8r.com/users/william/" class="link bumpright">william</a></p>
<h2>Inspiration:</h2>
<p>This website was partially inspired by a homework assignment I gave my students. The assignment was to find something in the news, on TV, in a magazine, etc. that was relevant to the topics discussed in class. I liked this assignment because it helped students to appreciate that the concepts discussed in class apply outside of the ivory tower in their day-to-day lives. I also liked how the assignment inspired discussions both inside and outside the classroom. Despite my appreciation for the assignment, there were a couple aspects I didn't like. Some students would email me links, others would post links on private forums, others would upload screenshots to a course management system, and others would hand me printouts or find other incredibly inventive ways to turn in their assignments. The variety of submissions made keeping track of who turned in what fairly difficult, especially when a student would hand me an assignment on my way to lunch. Although I still accept physical content, this site makes it easier for my students to submit and discuss content and much easier for me to keep track of electronic submissions. Second, and more importantly, when students submitted contents or discussed them on a private forum, we missed out on opportunities to learn from and share with others interested in these topics. This site addresses these shortcomings as well by allowing users from around the globe to submit and discuss contents that they find relevant to their areas of interest.</p>
<h2> Scope:</h2>
<p>This site is not intended to be a place to catch up with friends, nor a place to share the latest meme. If that's what you're looking for, try elsewhere. Instead, the site was primarily designed to help people find, organize, discuss, and share academically interesting non-academic media relevant to their interests with some extra features to help instructors and students engage in meaningful collabor8ive learning. We might be short on style, but we're aiming to be long on function.</p>
END;
?>